sfdx-framework/mdapi/unpackaged/objects/baf_DomainActionBinding__mdt.object
<CustomObject>
    <fields>
        <fullName>DomainAction__c</fullName>
        <inlineHelpText>Which class should be executed when the data change occurs.</inlineHelpText>
        <label>Domain Action</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsAsync__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>If True and the Trigger Stage is After, then the Domain Action will be executed as a Future.</inlineHelpText>
        <label>Is Asynchronous</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Sequence__c</fullName>
        <defaultValue>100</defaultValue>
        <inlineHelpText>The order Domain Actions should execute in, within the scope of a Trigger execution.</inlineHelpText>
        <label>Sequence</label>
        <precision>5</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TriggerChange__c</fullName>
        <defaultValue>&quot;Update&quot;</defaultValue>
        <inlineHelpText>What data change caused the Trigger to fire?</inlineHelpText>
        <label>Trigger Change</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Insert</fullName>
                    <default>true</default>
                    <label>Insert</label>
                </value>
                <value>
                    <fullName>Update</fullName>
                </value>
                <value>
                    <fullName>Delete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TriggerStage__c</fullName>
        <defaultValue>&quot;Before&quot;</defaultValue>
        <inlineHelpText>Whether the SObject&apos;s data change should be reacted to Before or After the data change is applied.</inlineHelpText>
        <label>Trigger Stage</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Before</fullName>
                    <default>true</default>
                    <label>Before</label>
                </value>
                <value>
                    <fullName>After</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TriggeredSObject__c</fullName>
        <defaultValue>&quot;Account&quot;</defaultValue>
        <inlineHelpText>The SObject data is changing on.</inlineHelpText>
        <label>Triggered SObject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Domain Action Binding</label>
    <pluralLabel>Domain Action Bindings</pluralLabel>
</CustomObject>

sfdx-framework/mdapi/unpackaged/classes/baf_DomainActionBindingsSelector.cls
/**
 * Executes SOQL against baf_DomainActionBinding__mdt
 */
public without sharing class baf_DomainActionBindingsSelector extends baf_SObjectSelector {
    public baf_DomainActionBindingsSelector() { super(baf_DomainActionBinding__mdt.SObjectType); }

    // implement required GetDefaultFields() method
    public override Set<Schema.SObjectField> GetDefaultFields() {
        return new Set<Schema.SObjectField> {
            baf_DomainActionBinding__mdt.TriggeredSObject__c,
            baf_DomainActionBinding__mdt.TriggerStage__c,
            baf_DomainActionBinding__mdt.TriggerChange__c,
            baf_DomainActionBinding__mdt.DomainAction__c,
            baf_DomainActionBinding__mdt.Sequence__c,
            baf_DomainActionBinding__mdt.IsAsync__c
        };
    }

    // implement required GetDefaultOrderBy() method
    public override List<baf_iOrderBy> GetDefaultOrderBy() {
        return new List<baf_iOrderBy> {
            baf_OrderBy.Ascending(baf_DomainActionBinding__mdt.IsAsync__c),
            baf_OrderBy.Ascending(baf_DomainActionBinding__mdt.Sequence__c),
            baf_OrderBy.Ascending(baf_DomainActionBinding__mdt.DomainAction__c)
        };
    }

    /**
     * Query for retrieving Trigger-specific DomainAction bindings
     * @param  targetSObject String     The SObject the Trigger is executing on
     * @param  process       stage      Before/After
     * @param  action        action     Insert/Update/Delete
     * @return  List of baf_DomainActionBinding__mdt entries
     */
    public List<baf_DomainActionBinding__mdt> GetForTrigger(String targetSObject, String stage, String change) {
        baf_iQueryFactory qf = GetQueryFactory()
            .WithCriteria(baf_Criteria.Equals(baf_DomainActionBinding__mdt.TriggeredSObject__c, targetSObject))
            .WithCriteria(baf_Criteria.Equals(baf_DomainActionBinding__mdt.TriggerStage__c, stage))
            .WithCriteria(baf_Criteria.Equals(baf_DomainActionBinding__mdt.TriggerChange__c, change));
        // THE PROCESS BELOW SHOULD ONLY BE REPEATED FOR CMDT SOBJECTS
        // YOU CAN NOT INSERT CMDT DURING A UNIT TEST, SO THIS HACK LETS THE UNIT TESTS HAPPEN
        // DO NOT REPEAT THIS PATTERN IN A NORMAL SOBJECT SELECTOR
        if (Test.isRunningTest()) {
            String sObjectName = Account.getSObjectType().getDescribe().getName();
            return new List<baf_DomainActionBinding__mdt>{
                new baf_DomainActionBinding__mdt(
                    TriggeredSObject__c = sObjectName,
                    TriggerStage__c = 'Before',
                    TriggerChange__c = 'Insert',
                    DomainAction__c = 'baft_SObjectDomain.testDomainActionOne',
                    Sequence__c = 10
                ),
                new baf_DomainActionBinding__mdt(
                    TriggeredSObject__c = sObjectName,
                    TriggerStage__c = 'Before',
                    TriggerChange__c = 'Insert',
                    DomainAction__c = 'baft_SObjectDomain.testDomainActionOnenTwo',
                    Sequence__c = 10
                )
            };
        } else {
            return (List<baf_DomainActionBinding__mdt>) qf.Execute();
        }
    }
}